name: BountyHead
version: 1.3.1-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.bountyhead.BountyHead
description: Head economy and monopoly.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  bountyhead:
    description: BountyHead main help command.
    aliases: [bounty, bh]
permissions:
  bountyhead.*:
    default: op
    children:
      bountyhead.usesign: true
      bountyhead.makesign: true
      bountyhead.reload: true
      bountyhead.placebounty: true
      bountyhead.removebounty: true
  bountyhead.usesign:
    default: false
  bountyhead.makesign:
    default: false
  bountyhead.reload:
    default: false
  bountyhead.placebounty:
    default: false
  bountyhead.removebounty:
    default: false