name: BountyHead
version: 1.2.2-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.bountyhead.BountyHead
description: Head economy and monopoly.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  bounty:
    description: Place a bounty on someone's head.
  bountyhead:
    description: Admin command help.
permissions:
  bountyhead.*:
    default: op
    children:
      bountyhead.sell: true
      bountyhead.makesign: true
      bountyhead.reload: true
      bountyhead.placebounty: true
      bountyhead.removebounty: true
  bountyhead.sell:
    default: false
  bountyhead.makesign:
    default: false
  bountyhead.reload:
    default: false
  bountyhead.placebounty:
    default: false
  bountyhead.removebounty:
    default: false